### ISSUE TITLE
nv.models.multiBarHorizontalChart

### ISSUE THREAD

**Issue by robrez** [RenatoUtsch/poly-nvd3#2]
It looks like you could get away with extending multiBarChart instead of abstractChart and just swapping out the nvModel...

[Check out my fork](https://github.com/robrez/poly-nvd3/commit/7abcc6f5391cf38a21ef7475841f2c0206046d90)

If you were going to do it, would you take this approach or would you extends abstractChart.

**Comment by RenatoUtsch** [comment]
Very good. Probably the line charts can be done like that too. Can you make a pull request?

**Comment by robrez** [comment]
[Here it is - #3](https://github.com/RenatoUtsch/poly-nvd3/pull/3).

**Comment by RenatoUtsch** [comment]
Thanks!

I'll close the issue.
