### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by adben** [RenatoUtsch/poly-nvd3#7]
On Chrome and Firefox works ok. Is there any extra configuration to make it work on safari 9+?

**Comment by RenatoUtsch** [comment]
I was surprised to discover that safari is as bad as IE in compatibility
with new standards. I had to make some workarounds in my production code to
make it work with safari bugs.

However, on the next 7 days I will be too busy to take a look at what needs
to be done. On Wednesday next week I can take a better look at this
(remember me if I don't!).

Em Seg, 9 de nov de 2015 15:08, Adolfo Benedetti notifications@github.com
escreveu:

**Comment by adben** [comment]
I made a mistake, the test in firefox is failing as well, pretty weird indeed, but actually I think booth issues are related; somehow the width and height properties are not being passed to the final svg(but to the parent div, and not getting inherited),... perhaps are those issues related?

<img width="1034" alt="screen shot 2015-11-17 at 16 54 01" src="https://cloud.githubusercontent.com/assets/209442/11216590/4234b86a-8d4c-11e5-8534-a88fa69a3b4b.png">

**Comment by alefwmm** [comment]
I discovered that you must include nv.d3.min.css on your website root index.html, in order to prevent _shadow dom_ to hide _nvd3_ styles. Otherwise it did not work.

**Comment by alefwmm** [comment]
I discovered that you must include nv.d3.min.css on your website root index.html, in order to prevent *shadow dom* to hide *nvd3* elements. Otherwise it did not work.

**Comment by RenatoUtsch** [comment]
I'm closing this, if it is not fixed by v1.4.2 then please open another issue.
